### ISSUE TITLE
Discord: invitation is invalid

### ISSUE THREAD

**Issue by snxx-lppxx** [toitlang/toitlang.org#4]
There is no permanent link to the [discord server](https://github.com/toitlang/toitlang.org/blob/dd1beff4bc8e9bde98a005717ede5eb06405b6fe/src/lib/Footer.svelte#L22).

**Comment by floitsch** [comment]
Thanks for letting us know.
Fixed in c465eb424e62bf53a3f4f621777034593d1dc2e3

**Comment by floitsch** [comment]
Reopened to be sure we don't use the same broken link on toitlang.org.

**Comment by floitsch** [comment]
Couldn't find a reference to discord on toitlang.org.
If I'm wrong, please reopen.

**Comment by floitsch** [comment]
Missed it. It's in the footer.
